import type { AARReportData } from "../types/exercise";
import { analyzeAAR, displayValue, formatAARTime, messageSecond, responseTimes, wallTime } from "./aar";

/** Escapes all recorded content, including rationale and radio text, before printing. */
const escape = (value: unknown) => String(value ?? "Not available").replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const list = (values?: string[]) => values?.length ? `<ul>${values.map(value => `<li>${escape(value)}</li>`).join("")}</ul>` : `<p>${values ? "None recorded." : "Not available"}</p>`;

export function reviewPrintHTML(report: AARReportData): string {
  const analysis = analyzeAAR(report);
  const transitions = (kind: "radio" | "map") => analysis[kind].map(state => `<li>${formatAARTime(state.second, true)} — ${escape(state.state)} · ${state.duration.toFixed(1)}s${state.delay == null ? "" : ` · delay ${state.delay}s`}${state.recovery == null ? "" : ` · recovery after ${state.recovery.toFixed(1)}s`}</li>`).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>TACTICAL-SIM AAR · ${escape(report.exerciseId)}</title><style>body{font:12px/1.6 Arial,sans-serif;color:#243229;padding:25px;max-width:960px;margin:auto}h1{font-size:24px}h2{font-size:17px;margin-top:25px;border-bottom:2px solid #84936d}h3{font-size:14px}article{border:1px solid #bbc2ae;padding:12px;margin:12px 0;break-inside:avoid}p,li,td{overflow-wrap:anywhere;white-space:pre-wrap}table{border-collapse:collapse;width:100%;font-size:11px}th,td{border-bottom:1px solid #bbc2ae;text-align:left;padding:8px;vertical-align:top}small{color:#536348}@media print{body{padding:0}@page{margin:16mm}}</style></head><body><small>TACTICAL-SIM / AFTER-ACTION REVIEW / ${report.isFinal ? "FINAL RECORD" : "LIVE PREVIEW"}</small><h1>${escape(report.scenarioName)}</h1><p>${escape(report.exerciseId)} · ${escape(report.teamName)}${report.trainingArea ? ` · ${escape(report.trainingArea.name)}` : ""}</p><p>Started: ${escape(wallTime(report.startedAt))}\nEnded: ${escape(wallTime(report.completedAt))}\nSimulation duration: ${formatAARTime(report.durationSeconds, true)}\nStatus: ${escape(report.status ?? (report.isFinal ? "completed" : "in progress"))}\nReview scope: ${escape(displayValue(report.reviewScope))}</p><h2>Objective observations</h2><p>${escape(analysis.summary)}\nAverage response latency: ${analysis.averageLatency === null ? "Not available" : `${analysis.averageLatency.toFixed(1)}s (${analysis.measuredResponses} decisions timed)`}\nRadio availability (not offline): ${analysis.radioAvailableSeconds === null ? "Not available" : `${analysis.radioAvailableSeconds.toFixed(1)}s`}\nInformation requests: Not available. No structured request events are recorded.</p><h2>Decision timeline</h2><table><thead><tr><th>Time</th><th>Category</th><th>Event / detail</th></tr></thead><tbody>${analysis.timeline.map(event => `<tr><td>${formatAARTime(event.second, true)}</td><td>${escape(event.category)}</td><td><strong>${escape(event.title)}</strong><br>${escape(event.description)}</td></tr>`).join("")}</tbody></table><h2>Individual decision analysis</h2>${report.decisions.map((decision, index) => {
    const times = responseTimes(report, decision);
    return `<article><h3>Decision #${index + 1} · ${escape(decision.selectedActionLabel)}</h3><p>Trainee: ${escape(decision.traineeId)}\nEvent time: ${formatAARTime(times.event, true)}\nRequired: ${formatAARTime(times.required, true)}\nSubmitted: ${formatAARTime(times.submitted, true)}\nLatency: ${times.latency === null ? "Not available" : `${times.latency.toFixed(1)}s`}\nConfidence: ${escape(displayValue(decision.confidence))}\nRadio: ${escape(decision.communicationState)} · Map: ${escape(displayValue(decision.mapStatus))}\nReliability: ${escape(displayValue(decision.informationSnapshot?.reliability))}</p><h3>Rationale</h3><p>${escape(decision.rationale)}</p><h3>Available at submission</h3>${list(decision.availableInformation)}<h3>Unavailable / degraded at submission</h3>${list(decision.unavailableInformation)}<p>Available report IDs: ${escape(decision.informationSnapshot?.reportIds?.join(", "))}</p></article>`;
  }).join("") || "<p>No decisions recorded.</p>"}<h2>Communication and map transitions</h2><h3>Radio</h3><ul>${transitions("radio") || "<li>Not available</li>"}</ul><h3>Map</h3><ul>${transitions("map") || "<li>Not available</li>"}</ul><h2>Team communication and information reliability</h2><p>${analysis.messages.length} transmissions · ${report.stats.messagesDelivered} delivered · ${report.stats.messagesDelayed} delayed · ${report.stats.messagesDropped} dropped · ${analysis.conflicts} marked conflicting.</p>${analysis.messages.map(message => `<article><h3>${escape(message.sender)} → ${escape(message.recipient ?? "Recipient not recorded")} · ${escape(message.deliveryStatus)}</h3><p>Generated: ${formatAARTime(messageSecond(message), true)} · Received: ${message.deliveryStatus === "DELIVERED" ? formatAARTime(messageSecond(message, true), true) : "Not delivered"}\nReliability: ${escape(message.isConflicting ? "Conflicting" : displayValue(message.reliability))} · Confirmation: ${message.confirmed === true ? "Confirmed" : message.confirmed === false ? "Unconfirmed" : "Not recorded"}\nConflict group: ${escape(message.conflictGroupId)}</p><p>${escape(message.content)}</p></article>`).join("")}<h2>Review summary</h2><p>${escape(analysis.summary)}</p><small>Recorded outcomes only. No tactical correctness or performance score is assigned. Final debriefs may reveal undelivered report contents; decision snapshots exclude later and undelivered information. Latencies use simulation time.</small></body></html>`;
}

export function printReview(report: AARReportData): boolean {
  const popup = window.open("", "_blank");
  if (!popup) return false;
  popup.opener = null;
  popup.document.write(reviewPrintHTML(report));
  popup.document.close();
  popup.focus();
  popup.print();
  return true;
}
