const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const original = require.extensions['.ts'];
require.extensions['.ts'] = (module, filename) => {
  const compiled = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, esModuleInterop: true, target: ts.ScriptTarget.ES2022 } });
  module._compile(compiled.outputText, filename);
};
const { LocalSimulationEngine } = require('../src/simulation/lib/simulation.ts');
const { analyzeAAR, allMessages, reportAvailability, responseTimes, decisionsCSV, formatAARTime, messageSecond, saveLocalReport, localReportKey } = require('../src/simulation/lib/aar.ts');
const { isServerAARReport } = require('../src/simulation/lib/sharedProtocol.ts');
const { reviewPrintHTML } = require('../src/simulation/lib/aarPrint.ts');
const engine = new LocalSimulationEngine('aar-test');
try {
  assert.equal(engine.generateAAR().startedAt, null, 'pending practice has no fabricated start');
  assert.equal(engine.generateAAR().completedAt, null);
  engine.start(); engine.dispose(); engine.tick(1.2);
  engine.applyInstructorInject('set_comms', { status: 'delayed', delay: 2 });
  engine.applyInstructorInject('conflicting_report');
  engine.tick(2);
  const received = engine.getState().messages.filter(m => m.isConflicting);
  assert.equal(received.length, 2);
  assert.ok(received.every(m => m.wasDelayed && m.deliveredSecond === 3.2));
  engine.applyInstructorInject('outdate_map');
  const pending = engine.sendRadioMessage('Bravo', 'TEAM_BRAVO', 'Report not yet received');
  engine.applyInstructorInject('set_comms', { status: 'offline' });
  const lost = engine.sendRadioMessage('Alpha', 'TEAM_ALPHA', 'Dropped intelligence');
  engine.applyInstructorInject('decision_point', { title: 'Verify reports', options: [{ id: 'hold', label: 'Hold and verify' }] });
  engine.tick(1.4);
  const decision = engine.submitDecision('Hold and verify', 'Sources conflict and current positions are unavailable.', 'medium', 'Commander', 'hold');
  const frozen = structuredClone(decision);
  assert.ok(Math.abs(decision.responseLatencySeconds - 1.4) < 1e-9);
  assert.equal(decision.mapStatus, 'outdated');
  assert.equal(decision.communicationState, 'offline');
  assert.equal(decision.informationSnapshot.reliability, 'conflicting');
  assert.ok(!decision.informationSnapshot.reportIds.includes(pending.id));
  assert.ok(!decision.availableInformation.some(info => info.includes('Report not yet received') || info.includes('Dropped intelligence')));
  engine.tick(1);
  engine.applyInstructorInject('set_comms', { status: 'normal' });
  engine.applyInstructorInject('restore_map');
  const future = engine.sendRadioMessage('Sensor', 'INTELLIGENCE', 'Later intelligence');
  engine.end();
  assert.throws(() => engine.submitDecision('Late decision', 'After completion', 'low'), /completed records cannot be changed/);
  const final = engine.generateAAR();
  engine.applyInstructorInject('restore_radio');
  engine.applyInstructorInject('set_comms', { status: 'normal' });
  assert.deepEqual(engine.generateAAR(), final, 'instructor injects cannot modify a completed local record');
  assert.deepEqual(final.decisions[0], frozen, 'later events never mutate decision snapshot');
  assert.ok(isServerAARReport(final, 'aar-test'), 'local and shared reviews retain the same validated contract');
  const corrupt = structuredClone(final);
  corrupt.decisions[0].informationSnapshot.reportIds = 42;
  assert.equal(isServerAARReport(corrupt, 'aar-test'), false, 'invalid optional snapshot metadata cannot crash the review');
  assert.equal(reportAvailability(final, final.messages.find(m => m.id === future.id), frozen), 'unavailable');
  assert.equal(reportAvailability(final, final.messages.find(m => m.id === pending.id), frozen), 'unavailable', 'delivered later is not available at decision');
  assert.equal(reportAvailability(final, final.messages.find(m => m.id === lost.id), frozen), 'unavailable');
  assert.equal(reportAvailability(final, received[0], frozen), 'available');
  const analysis = analyzeAAR(final);
  assert.equal(analysis.timeline.filter(event => event.decisionId === decision.id).length, 1, 'decision log and record are not duplicated');
  assert.equal(analysis.conflicts, 2);
  assert.equal(final.stats.messagesDelayed, 3, 'delay history survives delivery');
  assert.ok(analysis.radio.some(interval => interval.recovery > 0));
  assert.ok(analysis.averageLatency > 1.39 && analysis.averageLatency < 1.41);
  const duplicatePending = structuredClone(final);
  duplicatePending.pendingMessages.push(final.messages[0]);
  assert.equal(allMessages(duplicatePending).length, final.messages.length, 'pending array duplication never inflates counts');
  const legacy = structuredClone(decision);
  delete legacy.responseLatencySeconds; delete legacy.decisionRequiredSecond; delete legacy.decisionEventSecond;
  delete legacy.informationSnapshot;
  legacy.decisionPointId = 'unknown';
  assert.equal(responseTimes(final, legacy).latency, null, 'unrelated nearby event cannot create a response latency');
  const equalTime = { ...future, deliveredSecond: legacy.simulationSecond };
  assert.equal(reportAvailability({ ...final, fullEventLog: [] }, equalTime, legacy), 'unknown', 'same-time legacy availability is unknown without ordering');
  assert.equal(messageSecond({ timestampGenerated: 1720000000000, formattedTime: '01:02', timestampDelivered: undefined }), 62, 'legacy wall milliseconds are not treated as simulation time');
  assert.equal(messageSecond({ timestampGenerated: 0.4 }), 0.4);
  assert.equal(formatAARTime(59.96, true), '01:00.0', 'fraction rounding carries into minutes');
  assert.match(decisionsCSV({ ...final, decisions: [{ ...decision, rationale: '=HYPERLINK("example")' }] }), /'=HYPERLINK/, 'spreadsheet formulas are escaped');
  const printed = reviewPrintHTML({ ...final, decisions: [{ ...decision, rationale: '<script>alert("injected")</script>' }] });
  assert.ok(printed.includes('&lt;script&gt;') && !printed.includes('<script>'), 'print export escapes recorded content');
  assert.ok(printed.includes('Decision timeline') && printed.includes('Unavailable / degraded at submission') && printed.includes('Team communication'));
  const storage = new Map();
  global.localStorage = { setItem: (key, value) => storage.set(key, value) };
  assert.ok(saveLocalReport(final, 'account-a'));
  assert.notEqual(localReportKey('aar-test', 'account-a'), localReportKey('aar-test', 'account-b'));
  engine.reset();
  assert.equal(engine.generateAAR().startedAt, null);
  assert.equal(engine.generateAAR().completedAt, null);
  assert.deepEqual(final.decisions[0], frozen, 'reset does not mutate previously exported report');
  console.log('PASS: complete local AAR flow, fractional latency, immutable knowledge, delayed/dropped/future exclusions, legacy records, deduplication, recovery, CSV escaping and account-scoped storage');
} finally { engine.dispose(); require.extensions['.ts'] = original; delete global.localStorage; }
